name: Build Image

on:
  workflow_dispatch:
    inputs:
      app_dir:
        required: false
        type: string
        default: .
        description: Must not have / at the end
      dockerfile_path:
        required: false
        default: Dockerfile
        type: string
        description: Relative path

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Get commit hash
        id: commit-hash
        working-directory: ${{ inputs.app_dir }}
        run: echo "commit=$(git rev-parse HEAD)" >>"${GITHUB_OUTPUT}"

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.app_dir }}
          file: ${{ inputs.app_dir }}/${{ inputs.dockerfile_path }}
          push: true
          tags: |
            ghcr.io/${{ vars.github_repository }}:latest
            ghcr.io/${{ vars.github_repository }}:${{ steps.commit-hash.outputs.commit }}
