name: Commitlint

on:
  push:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Validate commit
        run: npx commitlint --last
